apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes-producer
  labels:
    app: springboot-kubernetes-producer
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes-producer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-kubernetes-producer
    spec:
      containers:
        - name: springboot-kubernetes-producer
          image: 'alessiozubiani1996/springboot-kubernetes-producer:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: producer
            - name: MYSQL_URL
              value: 'jdbc:mysql://mysql:3306/producer?allowPublicKeyRetrieval=true'
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /k8s-producer/actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-producer
spec:
  selector:
    app: springboot-kubernetes-producer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer