# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-kubernetes
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
        - name: app
          image: alessiozubiani1996/springboot-kubernetes:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent

---

# Service definition
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
spec:
  selector:
    app: springboot-kubernetes
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer