server:
  port: 8080
  servlet:
    context-path: /k8s-producer

spring:
  application:
    name: springboot-kubernetes-producer
  
  jpa:
    show-sql: true
  datasource:
    url: ${MYSQL_URL}?allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: 'health,metrics,prometheus'
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true